### PR TITLE
Feature/compose updates

### PR DESCRIPTION
**Pull request by abunur**
Note: this pr fixes (many) crashes. The app didn't work at all for me, after adding the APP ID and token from the portal - it just crashed. It also has a bunch of code clean up.

However, after these changes, while the app doesn't crash, creating a new task, doesn't show the new task in the UI. I don't have time right now to investigate this further. 

Feel free to not merge this PR, but perhaps use it as a starting point. As is though it doesn't seem the Compose tutorial app will run at all without an update.
Tested using the current release of Android Studio (Electric Eel) and Android 13

I didn't update the gradle version, or any of the library versions (they all need updating, but this will likely cascade to many other updates)

### CODE REVIEW

**Review by kndoshn — APPROVED** [review]
We need to fix the tutorial documentation too since this app should be the completed version of the tutorial.

**Comment by okdistribute** [comment]
related to https://github.com/getditto/samples/issues/75

**Comment by abunur** [comment]
@okdistribute @texasRanger09 do you prefer this PR merge or just hang out until the rest of the work can be done on this tutorial? My thought is not to merge it, not to close it, just leave it open for now if that's ok

**Comment by okdistribute** [comment]
Yeah, let's leave it open and then tackle it over the next couple weeks

**Comment by okdistribute** [comment]
I'm not sure what to do about these conflicts.

**Comment by okdistribute** [comment]
thanks!

**Comment by abunur** [comment]
created new cherry pick branch from main

**Comment by abunur** [comment]
replaced by: https://github.com/getditto/samples/tree/feature/compose_updates_cherrypick

**Pull request closed without merging**
