### PR TITLE
Feature/tasks kotlin v4

### PR DESCRIPTION
**Pull request by abunur**
This PR does the following for the Kotlin TODO sample app:

- the app now compiles and runs - it would not even compile before
- the app is compatible with Android 13
- migrated from Kotlin synthetics to Jetpack view binding, as Kotlin synthetics is no longer supported. 

This PR does NOT update to V4. That will be done in a separate PR

### CODE REVIEW

**Comment by abunur** [comment]
blocked by https://github.com/getditto/samples/pull/101

**Comment by okdistribute** [comment]
Woo looks like we have some conflicts, can you resolve them then I can review?

**Comment by abunur** [comment]
> Woo looks like we have some conflicts, can you resolve them then I can review?

I think we should wait until https://github.com/getditto/samples/pull/101 is merged then see if there are still any conflicts and resolve them

**Comment by kndoshn** [comment]
I opened #102 instead of this PR, so I'm closing this now.

**Pull request closed without merging**
